### ISSUE TITLE
'official' python script

### ISSUE THREAD

**Issue by dvand** [marcelm/radonwave#2]
Not really and issue but in case you haven't seen this:

https://airthings.com/raspberry-pi/

**Comment by marcelm** [comment]
No, I haven’t seen it, thanks!

This surprised me a bit because I most definitely searched the web before writing my own script. Fortunately, it turns out that I [published my script on January 26th](https://github.com/marcelm/radonwave/commit/b5851c7ee7abdf3acbbccf003d70e25951981e2b), while the Airthings web page is from Feb. 2nd. So at least while I was doing it, it wasn’t duplicate effort.

I’ll add a link to the README of course.
